services:
  postgres:
    image: postgres:16-alpine
    container_name: flash_buy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flash_buy_db
    ports:
      - "5435:5432"
    volumes:
      - flash_buy_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: flash_buy_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - flash_buy_redis_data:/data

volumes:
  flash_buy_postgres_data:
  flash_buy_redis_data:
